---
# Open up ports to communicate with the app.
kind: Service
apiVersion: v1
metadata:
  name: fileupload-service
  namespace: default
  annotations:
    description: Exposes and load balances the application pods.
    created-by: jacob.wang
  labels:
    name: fileupload-service
    part-of: tno
    version: 1.0.0
    component: fileupload-service
    managed-by: kustomize
spec:
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    part-of: tno
    component: fileupload-service
  sessionAffinity: None
  type: ClusterIP
